version: '3.7'

services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: api-solid-pg
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api-solid
